# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: aws-sqs-lambda-retrofit-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: aws
  runtime: java11
  region: us-east-1
  tracing:
    #apiGateway: true
    lambda: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: "*"
package:
  artifact: 'target/aws-sqs-lambda-retrofit-dev.jar'
 
functions:
  sqsDequeue:
    handler: com.serverless.Handler
    events:
      - sqs:
          arn:aws:sqs:us-east-1:XXXXXXXXXXXXXX:sqs-queue-retrofit
          #batchSize: 10
          #maximumBatchingWindow: 60
          #functionResponseType: ReportBatchItemFailures
